USE master
GO

CREATE DATABASE CinePlus
GO

USE CinePlus
GO

CREATE TABLE Peliculas(
idPelicula INT IDENTITY NOT NULL,
TituloPelicula VARCHAR(150) NOT NULL,
Sinopsis NVARCHAR(MAX) NULL,
Director VARCHAR(120) NULL,
Género VARCHAR(50) NULL,
Calificacion DECIMAL(5,1)NULL,
Poster image NULL,

PRIMARY KEY (idPelicula)
)

--Volcado de datos ***CAMBIAR LA DIRECCION DE LAS IMAGENES POR DONDE LAS TIENEN GUARDADAS***
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('La Tumba de las Luciernagas', 'Un adolescente se ve obligado a cuidar a su hermana menor después de que un bombardeo aliado durante la Segunda Guerra Mundial destruye su casa y mata a su madre.','Isao Takahata','Animación, Drama', 4.9, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\TumbaDeLasLuciernagas.jpg', SINGLE_BLOB)as T1))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('#VIVO','Una ciudad es infectada por un virus misterioso, haciendo que todo se salga de control y siendo puesta en cuarentena, dejando a dos sobrevivientes completamente aislados y luchando por vivir en una situación crítica.','Cho Il-hyeong','Cine de Zombies',3.0, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\Vivo.jpg', SINGLE_BLOB)as T2))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Batman: el caballero de la noche asciende','Ocho años después de asumir la culpa por la muerte de Harvey Dent y desaparecer en la noche, Batman se ve obligado a salir del exilio autoimpuesto gracias a una ladrona astuta y a un terrorista despiadado.','	
Christopher Nolan','Accion, Aventura, Drama',4.7, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\BatmanNoche.jpg', SINGLE_BLOB)as T3))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('La Colina de las Amapolas','La historia se desarrolla en el Japón de 1963. Umi Matsuzaki es una estudiante de secundaria que, en ausencia de su madre, cuida a sus dos hermanos menores, Sora y Riku. Un día conoce a Shun Kazama, un muchacho miembro del club de periodismo, y Shirō Mizunuma, presidente del consejo estudiantil. Juntos descubrirán una forma de convivir entre el turbio pasado, el difícil presente y el esperanzador futuro en un momento del tiempo donde Japón empezaba a levantar cabeza','Gorō Miyazaki','Animación, Drama',4.8, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\ColinaAmapola.jpg', SINGLE_BLOB)as T4))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('El cuento de la princesa Kaguya','Encontrada dentro de un brillante tallo de bambú por un viejo cortador de bambú y su esposa, una niña diminuta se convierte rápidamente en una hermosa joven que cautiva a todos los que la conocen, pero debe enfrentar su destino.','Isao Takahata','Animación, Drama',4.8,(SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\KaguyaHime.jpg', SINGLE_BLOB)as T5))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Mujercitas (2019)','En los primeros años que prosiguen a la guerra civil estadounidense, la vida de una familia se ve alterada para siempre luego de que Beth, una de las hermanas, revela que padece una terrible enfermedad.','Greta Gerwig','Drama, Romance',4.2, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\LittleWomen.jpg', SINGLE_BLOB)as T6))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('La princesa Mononoke','Un príncipe se ve involucrado en un conflicto entre una princesa del bosque y el abuso de la mecanización.','Hayao Miyazaki','Fantasía, Aventura, Drama',4.8, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\MononokeHime.jpg', SINGLE_BLOB)as T7))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Parásitos','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a impartir clases particulares en la adinerada casa de los Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, entablan una relación de resultados imprevisibles.',' Bong Joon-ho','Drama, Suspense, Humor negro',4.5, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\Parasite.jpg', SINGLE_BLOB)as T8))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Ponyo','Durante una excursión prohibida para ver el mundo de la superficie, una princesa pez de colores conoce a un niño llamado Sosuke, quien le pone el nombre de Ponyo. Ponyo quiere volverse un humano, y mientras crece su amistad, ella se vuelve más humana.','Hayao Miyazaki','Animación, Infatil',4.8,(SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\Ponyo.jpg', SINGLE_BLOB)as T9))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Recuerdos del Ayer','Una empleada de oficina recuerda su infancia mientras reflexiona sobre su estado de vida actual.',' Isao Takahata','Animación, Drama',4.7,(SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\RecuerdosDelAyer.jpg', SINGLE_BLOB)as T10))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('El Viaje de Chihiro','Perdida en el bosque, una niña (Rumi Hîragi) de 10 años conoce animales, fantasmas y criaturas extrañas.','Hayao Miyazaki','Aventura, Fantasía',5.0,(SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\SpiritedAway.jpg', SINGLE_BLOB)as T11))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Susurros del Corazón','Una joven estudiante amante de los libros descubre que todos los libros que ha elegido en la biblioteca han sido elegidos anteriormente por la misma persona. Así conoce a Seiji, un joven que está aprendiendo a fabricar violines.','Yoshifumi Kondo','Animación, Drama',4.9,(SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\SusurrosDelCorazon.jpg', SINGLE_BLOB)as T12))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('El Hombre Invisible','Un científico loco finge su suicidio y luego utiliza su invisibilidad para aterrorizar a su expareja, quien decide enfrentar al hombre invisible ella misma luego de que la policía no creyera su historia.','Leigh Whannell','Suspense, Ciencia Ficción',3.9, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\TheInvisibleMan.jpg', SINGLE_BLOB)as T13))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('Mi Vecino Totoro','La historia sigue a las estudiantes y hermanas Satsuke y Mei mientras se establecen en su casa de campo con su padre y esperan a que su madre se recupere de una enfermedad en un hospital del área. Cuando las hermanas exploran su nueva casa, descubren y hacen amistad con unos duendes juguetones, y en el bosque cercano encuentran a una enorme criatura conocida como Totoro.','Hayao Miyazaki','Animación, Infantil',4.8, (SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\Totoro.jpg', SINGLE_BLOB)as T14))
INSERT INTO Peliculas(TituloPelicula, Sinopsis, Director, Género, Calificacion, Poster) VALUES('El Viento se Levanta','Un amor de toda la vida por el vuelo inspira al ingeniero en aviación japonés Jiro Horikoshi, cuya ilustre carrera incluye la creación del avión de combate A6M de la Segunda Guerra Mundial.','Hayao Miyazaki','Drama Histórico',4.8,(SELECT *FROM OPENROWSET(BULK N'C:\Users\alexm\Documents\Desarrollo Software Propietario\Taller2\Posters\VientoSeLevanta.jpg', SINGLE_BLOB)as T15))

SELECT * FROM Peliculas