//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALLER_ASP_II.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int idPelicula { get; set; }
        public string TituloPelicula { get; set; }
        public string Sinopsis { get; set; }
        public string Director { get; set; }
        public string Género { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public byte[] Poster { get; set; }
    }
}
