//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALLER_ASP_II.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CinePlusEntities : DbContext
    {
        public CinePlusEntities()
            : base("name=CinePlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Peliculas> Peliculas { get; set; }
    
        public virtual ObjectResult<Ranking_Result> Ranking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ranking_Result>("Ranking");
        }
    }
}
