//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALLER_ASP_II.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int idPelicula { get; set; }
        public string TituloPelicula { get; set; }
        public string Sinopsis { get; set; }
        public string Director { get; set; }
        public string Género { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public byte[] Poster { get; set; }
    }
}
